//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using KanbanizeTool.Config;

namespace KanbanizeTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kanbanize.com/index.php/api/kanbanize")]
        public string KanbanizeUri {
            get {
                return ((string)(this["KanbanizeUri"]));
            }
            set {
                this["KanbanizeUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("153, 173, 153")]
        public global::System.Drawing.Color ColorTask {
            get {
                return ((global::System.Drawing.Color)(this["ColorTask"]));
            }
            set {
                this["ColorTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorBUG {
            get {
                return ((global::System.Drawing.Color)(this["ColorBUG"]));
            }
            set {
                this["ColorBUG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorImprovement {
            get {
                return ((global::System.Drawing.Color)(this["ColorImprovement"]));
            }
            set {
                this["ColorImprovement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TfsServerUri {
            get {
                return ((string)(this["TfsServerUri"]));
            }
            set {
                this["TfsServerUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TfsTaskLinkTemplate {
            get {
                return ((string)(this["TfsTaskLinkTemplate"]));
            }
            set {
                this["TfsTaskLinkTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TfsProjectName {
            get {
                return ((string)(this["TfsProjectName"]));
            }
            set {
                this["TfsProjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string KanbanizeApiKey {
            get {
                return ((string)(this["KanbanizeApiKey"]));
            }
            set {
                this["KanbanizeApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string KanbanizeBoardId {
            get {
                return ((string)(this["KanbanizeBoardId"]));
            }
            set {
                this["KanbanizeBoardId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TfsToKanbanizeAssigneeMapping {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TfsToKanbanizeAssigneeMapping"]));
            }
            set {
                this["TfsToKanbanizeAssigneeMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TfsUserName {
            get {
                return ((string)(this["TfsUserName"]));
            }
            set {
                this["TfsUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TfsDomainName {
            get {
                return ((string)(this["TfsDomainName"]));
            }
            set {
                this["TfsDomainName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(CustomPathSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TfsPassword {
            get {
                return ((string)(this["TfsPassword"]));
            }
            set {
                this["TfsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KanbanizeTfsTool")]
        public string SettingsKey {
            get {
                return ((string)(this["SettingsKey"]));
            }
            set {
                this["SettingsKey"] = value;
            }
        }
    }
}
